решение задания 2.1
splitrarrys/tki-141 pull request #4
Opened 2024-10-21 19:30 UTC by splitrarrys

2024-10-28 15:12 UTC, MarinaPaley requested changes
std::cout << "Hello World!\n";

2024-10-30 09:44 UTC, BalakinaEP requested changes

2024-10-30 09:44 UTC, BalakinaEP commented on еtask 2.1/еtask 2.1.c
> +}
`return 0;`

2024-10-30 09:44 UTC, BalakinaEP commented on еtask 2.1/еtask 2.1.c
> +double area_of_a_trapezoid(const double a, const double b, const double h)
почему a, b и h?

2024-10-31 19:43 UTC, splitrarrys commented on еtask 2.1/еtask 2.1.c
> +double area_of_a_trapezoid(const double a, const double b, const double h)
h это высота

2024-11-06 11:36 UTC, MarinaPaley requested changes
не исправили замечания

2024-11-07 19:09 UTC, splitrarrys commented on еtask 2.1/еtask 2.1.c
> +double area_of_a_trapezoid(const double a, const double b, const double h)
это общепринятые меры обозначания сторон (a,b) и высоты (h)

2024-11-13 08:58 UTC, BalakinaEP requested changes

2024-11-13 08:58 UTC, BalakinaEP commented on еtask 2.1/еtask 2.1.c
> +double area_of_a_trapezoid(const double a, const double b, const double h)
не соответствует прототипу функции

2024-11-18 11:07 UTC, merged